### ISSUE TITLE
Build fails due to multiple function identifiers not found

### ISSUE THREAD

**Issue by RedPanda4552** [gottyduke/DKUtil#10]
This issue actually stems from trying to set up [SF_PluginTemplate](https://github.com/gottyduke/SF_PluginTemplate) but the core issue at hand is specifically with DKUtil failing to build itself. Everything up to that point in the output suggests its healthy so I believe this is specific to this project.

It appears as though something is telling the compiler to forget stdlib exists? But, only very specific parts of it? It is saying functions such as `std::ranges::contains_subrange` among others do not exist. From there it proceeds to spiral of course into a bunch of other syntax errors as one might expect once symbols just, get magically ignored by the compiler I guess.

Reproduction steps: Follow the Requirements and Get Started sections of the [SF_PluginTemplate](https://github.com/gottyduke/SF_PluginTemplate) readme, using a fresh project with no modifications made to the sample main.cpp file. Issue will occur when running `cmake --build build`.

Edit: forgot to attach file
[DKUtil Build Error.txt](https://github.com/gottyduke/DKUtil/files/12644799/DKUtil.Build.Error.txt)

**Comment by gottyduke** [comment]
The problematic `std::ranges::contains_subrange` is a c++23 library feature, and only implemented in MSVC STL currently. Are you building with clang-cl per chance?

**Comment by RedPanda4552** [comment]
I was running `.\make-sln-msvc.bat` prior to `cmake --build build`, first line is also Microsoft Build Engine declaring its version. Strangely enough, it says "for .NET Framework"...

```
PS D:\Home\Development\C++\TestProject> cmake --build build
Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  CommonLibSF.vcxproj -> D:\Home\Development\C++\TestProject\build\CommonLibSF\CommonLibSF\Debug\CommonLibSF.lib
cl : command line warning D9002: ignoring unknown option '/Zc:enumTypes' [D:\Home\Development\C++\TestProject\build\TestProject.vcxproj]
cl : command line warning D9002: ignoring unknown option '/Zc:templateScope' [D:\Home\Development\C++\TestProject\build\TestProject.vcxproj]
  cmake_pch.cxx
D:\Home\Development\C++\TestProject\extern\DKUtil\include\DKUtil\Impl\Utility\string.hpp(123,23): error C2039: 'contains_subrange': is not a member of 'std::ranges' [D:\Home\Development\C++\TestProject\build\TestProject.vcxproj]
```

I had a look at VS to see if perhaps I was on an outdated MSVC but it looks like I am on the latest, "MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)". Cmake also running on the latest, 3.27.5.

**Comment by gottyduke** [comment]
MSBuild 17.2.1 is really outdated for c++23 standards. It's still in the big 6.0 SDK set. You should update the visual studio to the latest 17.7(current) or 17.9(preview), which is for 7.0 SDK and 8.0 SDK respectively.

**Comment by RedPanda4552** [comment]
Sure enough, I'm a fool and didn't realize VS itself was behind. Resolved, sorry for wasting your time.
