### ISSUE TITLE
Please make the funcInfo parameter in AddCaveHook optional

### ISSUE THREAD

**Issue by igromanru** [gottyduke/DKUtil#12]
While it's overall an useful feature to be able to call your function from a CaveHook, some developers might don't need the feature depending on the use case.  
While you can just use a blank function, I think it would be more optimal just to be able to leave the code completely out of it.  

My suggestion, for better usability, is to make multiple overloads of the function.
```
auto AddCaveHook(a_address, a_offset, a_code, a_flag);
auto AddCaveHook(a_address, a_offset, a_prolog, a_epilog, a_flag);
```
The first one takes only 1 code block and flag could be simply Before or After.  
The second works the same as the original function but without the function.

Since it's a "Util library" I find it nice when there are more options for developers to decide for themself what exactly they want.

**Comment by gottyduke** [comment]
I think what you are suggesting is `AddASMPatch`? Or please clarify me if I understood it wrong.

**Comment by igromanru** [comment]
Oh, I think you're right. I just couldn't determinate from `AddASMPatch`'s description that it can create a code cave.  
But now I see that it does it automatically on a condition:  
```
If the given target memory defined by offsets is less than the size of assembly patch, a trampoline will be utilized to fulfill the patch and setup the auto detour/return. This action requires a minimal target memory space of 0x5.
The bool paramter forward indicates whether to skip the rest of NOP after applying the patch.
```  
But then what is about the restoration of the original bytes in the created code cave? It's a feature of AddCaveHook, but I don't see such possibility in AddASMPatch, at least not from the description of it.

**Comment by gottyduke** [comment]
> But then what is about the restoration of the original bytes in the created code cave? It's a feature of AddCaveHook, but I don't see such possibility in AddASMPatch, at least not from the description of it.

You are right, I have not added a flag for `AddASMPatch`, when I first implemented it, I was thinking if people were patching asm by hand, they probably don't care about the original bytes or they'd just re-add them manually within patch. 

If this is what you think it's lacking, I could add it akin to the form of `AddCaveHook`, I can see the the advantage of letting developers decide whether want to use it or not.

**Comment by igromanru** [comment]
To be honest, I don't find the function names very intuitive at the moment. I have many years of experience hacking games and just by looking at the function names and their description for the first time, I haven't figured out which one I need for my use case.  This is basically the reason for my confusion.   
My suggestion would be, to make different function for different tasks, so the naming is consistent to what their do.  
For example:
PatchASM: Patches code on an address with your defined code
AddCodeCave: Creates a code cave with a trampoline to the code cave and back, restores original bytes in code cave before or after users code
AddDetourHook: Does basically exactly what AddCaveHook currently do.

**Comment by gottyduke** [comment]
Thank you for the valid points, I've been working on docs recently and will take that into account. As for function names I don't think I'll change them much yet, but I'll try to distinguish them with a better description.

**Comment by igromanru** [comment]
You could add new functions, that do less "magic" on their own and reuse existing functions as backbone or extract some logic to make them reusable.   

However, thanks for the patience. I think the original topic is resolved, I'll close the issue.
