### ISSUE TITLE
Can DKUtil be used outside of SE context?

### ISSUE THREAD

**Issue by igromanru** [gottyduke/DKUtil#15]
I wanted to make my mod be able to loaded with ASI Loader as well.  
From my understanding, if I simply rename my dll to .asi and put it in the Plugins folder, the ASI Loader simply loads the dll and calls typically DllMain. It works so far.  

And so far I see, without the Script Extender I can't use your tools (DKUtil) right?  
At least if I try to use my dll as ASI i get an error, if i try to use AddCaveHook as it is..
![Starfield__4z0c99OMJ6](https://github.com/gottyduke/DKUtil/assets/1902937/8c8728a6-0c9d-4185-999f-0e66655e2383)  

Are there any ways to make it work?  
You have some great tool set there, would be nice if they could be used without Script Extender.

**Comment by gottyduke** [comment]
This template has an asi_loader branch.

**Comment by igromanru** [comment]
Awesome, thanks you!
